version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    restart: on-failure
    ports:
      - 1001:8080
    environment:
      OAUTH_CLIENT_ID: your-client-id
      OAUTH_CLIENT_SECRET: your-secret
      CONFIG_URL: http://localhost:9301/api.json
      URL: http://localhost:9301/api.json
